### ISSUE TITLE
Doesnt work with JBL 500BT, Even though apple can read it's battery status

### ISSUE THREAD

**Issue by MagnusStrom** [jariz/Akku#111]
Title says it all.

**Comment by dstd** [comment]
It's not quite stable, but it works. Yesterday I just paired this headset and got the same issue as you. Tried to turn it off and on, but there was no luck.
However today I turned on the headset and is surprised seeing white icon of Akku 🤪
All that happened since previous attempt is a sleep of my macMini.

![1384BDAC-56D6-431A-B3D0-25DC4829BC84](https://user-images.githubusercontent.com/1444844/126455885-093fcd5d-4625-4a9e-989d-8e6a38942574.png)

**Comment by MagnusStrom** [comment]
Fixed it, how do i restart top bar apps

**Comment by plainsimplejs** [comment]
@dstd Your menu bar looks loaded. Wow! ❤️ Could you please share list of your menu bar apps? Or your mac setup guide maybe?
