### ISSUE TITLE
Why do you need to install a helper app separately?

### ISSUE THREAD

**Issue by Sridhar-Ananthanarayanan** [jariz/Akku#64]
While I see the explanation you have given, and given that your app won't work at all without your helper app (unlike it being a requirement for enabling a certain feature), why isn't it integrated within the main app itself?

**Comment by jariz** [comment]
As explained in the app itself, reading the battery levels requires privileged access. I have not found a way to do this without privileged access.

Instead of making the entire app run under privileged access, it is much more secure to have a separate, smaller app, that only runs the required privileged commands and nothing else (i.e. the helper), making the possible attack vector smaller incase a vulnerability is found within the app.

This is generally what apple recommends doing. You can read more about why this is a recommended practice in their guide:
https://developer.apple.com/library/archive/documentation/Security/Conceptual/SecureCodingGuide/Articles/AccessControl.html
